name: Build Release APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Auto Repair Android Scaffolding
        run: flutter create . --platforms=android --org=com.example

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Debug APK
        run: flutter build apk --debug

      - name: Print Exact APK SHA-1
        run: |
          echo "==================== REAL APK SHA-1 ===================="
          keytool -printcert -jarfile build/app/outputs/flutter-apk/app-debug.apk
          echo "========================================================"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: PaisaLoots-App-Release
          path: build/app/outputs/flutter-apk/app-debug.apk
